"""Initial schema

Revision ID: 001
Revises:
Create Date: 2025-01-15

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import JSON

revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # This will be auto-generated by running:
    # alembic revision --autogenerate -m "initial schema"
    # For now, we let SQLAlchemy create tables via Base.metadata.create_all()
    pass


def downgrade() -> None:
    pass
